export const CANINES_LOADING='CANINES_LOADING'
export const CANINES_BREED_IMAGES_LOADING='CANINES_BREED_IMAGES_LOADING'
export const CANINES_PULL='CANINES_PULL'
export const CANINES_DISPLAY='CANINES_DISPLAY'